/**
 * tweak-api
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tweak.model;

import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Category  {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("categoryId")
  private Double categoryId = null;
  @SerializedName("parentId")
  private Double parentId = null;
  @SerializedName("designId")
  private Double designId = null;
  @SerializedName("children")
  private List<Object> children = null;
  @SerializedName("parent")
  private Object parent = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getCategoryId() {
    return categoryId;
  }
  public void setCategoryId(Double categoryId) {
    this.categoryId = categoryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getParentId() {
    return parentId;
  }
  public void setParentId(Double parentId) {
    this.parentId = parentId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getDesignId() {
    return designId;
  }
  public void setDesignId(Double designId) {
    this.designId = designId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getChildren() {
    return children;
  }
  public void setChildren(List<Object> children) {
    this.children = children;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getParent() {
    return parent;
  }
  public void setParent(Object parent) {
    this.parent = parent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Category category = (Category) o;
    return (this.name == null ? category.name == null : this.name.equals(category.name)) &&
        (this.description == null ? category.description == null : this.description.equals(category.description)) &&
        (this.id == null ? category.id == null : this.id.equals(category.id)) &&
        (this.categoryId == null ? category.categoryId == null : this.categoryId.equals(category.categoryId)) &&
        (this.parentId == null ? category.parentId == null : this.parentId.equals(category.parentId)) &&
        (this.designId == null ? category.designId == null : this.designId.equals(category.designId)) &&
        (this.children == null ? category.children == null : this.children.equals(category.children)) &&
        (this.parent == null ? category.parent == null : this.parent.equals(category.parent));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (description == null ? 0: description.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (categoryId == null ? 0: categoryId.hashCode());
    result = 31 * result + (parentId == null ? 0: parentId.hashCode());
    result = 31 * result + (designId == null ? 0: designId.hashCode());
    result = 31 * result + (children == null ? 0: children.hashCode());
    result = 31 * result + (parent == null ? 0: parent.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Category {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  categoryId: ").append(categoryId).append("\n");
    sb.append("  parentId: ").append(parentId).append("\n");
    sb.append("  designId: ").append(designId).append("\n");
    sb.append("  children: ").append(children).append("\n");
    sb.append("  parent: ").append(parent).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
