/**
 * tweak-api
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tweak.model;

import java.util.*;
import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Customer  {
  
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("realm")
  private String realm = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("credentials")
  private Object credentials = null;
  @SerializedName("challenges")
  private Object challenges = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("emailVerified")
  private Boolean emailVerified = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("created")
  private String created = null;
  @SerializedName("lastUpdated")
  private String lastUpdated = null;
  @SerializedName("id")
  private Double id = null;
  @SerializedName("designs")
  private List<Object> designs = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRealm() {
    return realm;
  }
  public void setRealm(String realm) {
    this.realm = realm;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCredentials() {
    return credentials;
  }
  public void setCredentials(Object credentials) {
    this.credentials = credentials;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getChallenges() {
    return challenges;
  }
  public void setChallenges(Object challenges) {
    this.challenges = challenges;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getEmailVerified() {
    return emailVerified;
  }
  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreated() {
    return created;
  }
  public void setCreated(Date created) {
    this.created = created.toString();
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastUpdated() {
    return lastUpdated;
  }
  public void setLastUpdated(Date lastUpdated) {
    this.lastUpdated = lastUpdated.toString();
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getDesigns() {
    return designs;
  }
  public void setDesigns(List<Object> designs) {
    this.designs = designs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return (this.firstName == null ? customer.firstName == null : this.firstName.equals(customer.firstName)) &&
        (this.lastName == null ? customer.lastName == null : this.lastName.equals(customer.lastName)) &&
        (this.realm == null ? customer.realm == null : this.realm.equals(customer.realm)) &&
        (this.username == null ? customer.username == null : this.username.equals(customer.username)) &&
        (this.credentials == null ? customer.credentials == null : this.credentials.equals(customer.credentials)) &&
        (this.challenges == null ? customer.challenges == null : this.challenges.equals(customer.challenges)) &&
        (this.email == null ? customer.email == null : this.email.equals(customer.email)) &&
        (this.emailVerified == null ? customer.emailVerified == null : this.emailVerified.equals(customer.emailVerified)) &&
        (this.status == null ? customer.status == null : this.status.equals(customer.status)) &&
        (this.created == null ? customer.created == null : this.created.equals(customer.created)) &&
        (this.lastUpdated == null ? customer.lastUpdated == null : this.lastUpdated.equals(customer.lastUpdated)) &&
        (this.id == null ? customer.id == null : this.id.equals(customer.id)) &&
        (this.designs == null ? customer.designs == null : this.designs.equals(customer.designs));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (firstName == null ? 0: firstName.hashCode());
    result = 31 * result + (lastName == null ? 0: lastName.hashCode());
    result = 31 * result + (realm == null ? 0: realm.hashCode());
    result = 31 * result + (username == null ? 0: username.hashCode());
    result = 31 * result + (credentials == null ? 0: credentials.hashCode());
    result = 31 * result + (challenges == null ? 0: challenges.hashCode());
    result = 31 * result + (email == null ? 0: email.hashCode());
    result = 31 * result + (emailVerified == null ? 0: emailVerified.hashCode());
    result = 31 * result + (status == null ? 0: status.hashCode());
    result = 31 * result + (created == null ? 0: created.hashCode());
    result = 31 * result + (lastUpdated == null ? 0: lastUpdated.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (designs == null ? 0: designs.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  realm: ").append(realm).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  credentials: ").append(credentials).append("\n");
    sb.append("  challenges: ").append(challenges).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  emailVerified: ").append(emailVerified).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  created: ").append(created).append("\n");
    sb.append("  lastUpdated: ").append(lastUpdated).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  designs: ").append(designs).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
